// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminal.Admin.Database;

#nullable disable

namespace Terminal.Admin.Database.Migrations
{
    [DbContext(typeof(TerminalDbContext))]
    [Migration("20260127132651_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AggregationBlockPowerStatePowerCalculation", b =>
                {
                    b.Property<int>("AggregationBlockPowerStatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AggregationBlockPowerStatesId", "CalculationsId");

                    b.HasIndex("CalculationsId");

                    b.ToTable("AggregationBlockPowerStatePowerCalculation");
                });

            modelBuilder.Entity("AggregationBlockPowerUnit", b =>
                {
                    b.Property<int>("AggregationBlocksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerUnitsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AggregationBlocksId", "PowerUnitsId");

                    b.HasIndex("PowerUnitsId");

                    b.ToTable("AggregationBlockPowerUnit");
                });

            modelBuilder.Entity("AggregationBlockSupportService", b =>
                {
                    b.Property<int>("AggregationBlocksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportServicesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AggregationBlocksId", "SupportServicesId");

                    b.HasIndex("SupportServicesId");

                    b.ToTable("AggregationBlockSupportService");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressValueType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Multiplicator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P104Address")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PowerUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendAlways")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("PowerUnitId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.AggregationBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BaselineSupport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CepsDisconnected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CepsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cepsname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlSystemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExternalOperationPlanSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsCallUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PowerDivider")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderEAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AggregationBlocks");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.AggregationBlockPowerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaselineCalculationId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PVS")
                        .HasColumnType("REAL");

                    b.Property<double>("PdgTrend")
                        .HasColumnType("REAL");

                    b.Property<double>("RealPower")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("BaselineCalculationId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("AggregationBlockPowerStates");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogEvent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.BaselineCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaselineId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaselineValue")
                        .HasColumnType("REAL");

                    b.Property<double>("LowerLimit")
                        .HasColumnType("REAL");

                    b.Property<double>("RealResidualPower")
                        .HasColumnType("REAL");

                    b.Property<double>("UpperLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId");

                    b.ToTable("BaselineCalculations");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.BaselineValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("BaselineValues");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.CepsRequiredPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDirectionChange")
                        .HasColumnType("TEXT");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("CepsRequiredPowers");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.CertificationTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActivationPower")
                        .HasColumnType("REAL");

                    b.Property<int>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CertificationEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CertificationStart")
                        .HasColumnType("TEXT");

                    b.Property<double>("Pdg")
                        .HasColumnType("REAL");

                    b.Property<int?>("ReportFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Trend")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("ReportFileId");

                    b.HasIndex("SupportServiceId");

                    b.ToTable("CertificationTests");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.FinishedChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("SupportServiceId");

                    b.ToTable("FinishedChanges");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.InstructionCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinalPowerChanged")
                        .HasColumnType("INTEGER");

                    b.Property<double>("P_lowbnd")
                        .HasColumnType("REAL");

                    b.Property<double>("P_uppbnd")
                        .HasColumnType("REAL");

                    b.Property<double>("Pdg_trend")
                        .HasColumnType("REAL");

                    b.Property<double>("Psetp_del")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("aFRR")
                        .HasColumnType("REAL");

                    b.Property<double>("aFRR_act")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR5_act")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR_DAM")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR_DAP")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR_SAM")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR_SAP")
                        .HasColumnType("REAL");

                    b.Property<double>("mFRR_act")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("InstructionCalls");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.OfflineTelemetryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbCompositionFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchiveConfirmedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchiveCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ArchiveFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchiveRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArchiveUploadAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchiveUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("CepsUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompositionConfirmedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompositionCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompositionRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompositionUploadAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompositionUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AbCompositionFileId");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("ArchiveFileId");

                    b.ToTable("OfflineTelemetryReports");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.OperationPlanSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Afrr_negative")
                        .HasColumnType("REAL");

                    b.Property<double>("Afrr_positive")
                        .HasColumnType("REAL");

                    b.Property<int>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Mfrr_12_negative")
                        .HasColumnType("REAL");

                    b.Property<double>("Mfrr_12_negative_mb")
                        .HasColumnType("REAL");

                    b.Property<double>("Mfrr_12_positive")
                        .HasColumnType("REAL");

                    b.Property<double>("Mfrr_12_positive_mb")
                        .HasColumnType("REAL");

                    b.Property<double>("Mfrr_5")
                        .HasColumnType("REAL");

                    b.Property<double>("Pdg")
                        .HasColumnType("REAL");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseBaseline")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("FromDate", "ToDate");

                    b.ToTable("OperationPlanSlots");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.PowerCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AllowedDeviation")
                        .HasColumnType("REAL");

                    b.Property<int?>("CepsRequiredPowerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LowerLimit")
                        .HasColumnType("REAL");

                    b.Property<double>("OfferedPowerMax")
                        .HasColumnType("REAL");

                    b.Property<double>("OfferedPowerMin")
                        .HasColumnType("REAL");

                    b.Property<double>("ReportedPower")
                        .HasColumnType("REAL");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("TrendedPower")
                        .HasColumnType("REAL");

                    b.Property<double>("UpperLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("CepsRequiredPowerId");

                    b.HasIndex("TimeStamp");

                    b.ToTable("PowerCalculations");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.PowerUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CepsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlSystemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceCategory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FcrProvisioning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Power")
                        .HasColumnType("REAL");

                    b.Property<string>("PowerUnitCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PowerUnits");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.ReportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Finished")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuidStr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReportFiles");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.SupportService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportService");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.TelemetryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AggregationBlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("P104Address")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PowerUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AggregationBlockId");

                    b.HasIndex("MessageType");

                    b.HasIndex("PowerUnitId");

                    b.HasIndex("TimeStamp");

                    b.HasIndex("TimeStamp", "AggregationBlockId");

                    b.HasIndex("TimeStamp", "PowerUnitId");

                    b.ToTable("TelemetryLogs");
                });

            modelBuilder.Entity("AggregationBlockPowerStatePowerCalculation", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlockPowerState", null)
                        .WithMany()
                        .HasForeignKey("AggregationBlockPowerStatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.PowerCalculation", null)
                        .WithMany()
                        .HasForeignKey("CalculationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggregationBlockPowerUnit", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", null)
                        .WithMany()
                        .HasForeignKey("AggregationBlocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.PowerUnit", null)
                        .WithMany()
                        .HasForeignKey("PowerUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggregationBlockSupportService", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", null)
                        .WithMany()
                        .HasForeignKey("AggregationBlocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.SupportService", null)
                        .WithMany()
                        .HasForeignKey("SupportServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.Address", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("Addresses")
                        .HasForeignKey("AggregationBlockId");

                    b.HasOne("Terminal.Admin.Data.Models.PowerUnit", "PowerUnit")
                        .WithMany("Addresses")
                        .HasForeignKey("PowerUnitId");

                    b.Navigation("AggregationBlock");

                    b.Navigation("PowerUnit");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.AggregationBlockPowerState", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("AggregationBlockPowerStates")
                        .HasForeignKey("AggregationBlockId");

                    b.HasOne("Terminal.Admin.Data.Models.BaselineCalculation", "BaselineCalculation")
                        .WithMany()
                        .HasForeignKey("BaselineCalculationId");

                    b.Navigation("AggregationBlock");

                    b.Navigation("BaselineCalculation");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.BaselineCalculation", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.BaselineValue", "Baseline")
                        .WithMany()
                        .HasForeignKey("BaselineId");

                    b.Navigation("Baseline");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.BaselineValue", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("BaselineValues")
                        .HasForeignKey("AggregationBlockId");

                    b.Navigation("AggregationBlock");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.CepsRequiredPower", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("RequiredPowers")
                        .HasForeignKey("AggregationBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregationBlock");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.CertificationTest", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("CertificationsTests")
                        .HasForeignKey("AggregationBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.ReportFile", "ReportFile")
                        .WithMany()
                        .HasForeignKey("ReportFileId");

                    b.HasOne("Terminal.Admin.Data.Models.SupportService", "SupportService")
                        .WithMany()
                        .HasForeignKey("SupportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregationBlock");

                    b.Navigation("ReportFile");

                    b.Navigation("SupportService");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.FinishedChange", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("FinishedChanges")
                        .HasForeignKey("AggregationBlockId");

                    b.HasOne("Terminal.Admin.Data.Models.SupportService", "SupportService")
                        .WithMany()
                        .HasForeignKey("SupportServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AggregationBlock");

                    b.Navigation("SupportService");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.InstructionCall", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany()
                        .HasForeignKey("AggregationBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Terminal.Admin.Data.Models.ActiveAns", "ActiveAns", b1 =>
                        {
                            b1.Property<int>("InstructionCallId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Ans")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Slot")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InstructionCallId", "Id");

                            b1.ToTable("InstructionCalls");

                            b1.ToJson("ActiveAns");

                            b1.WithOwner()
                                .HasForeignKey("InstructionCallId");
                        });

                    b.OwnsMany("Terminal.Admin.Data.Models.ActivePowerUnit", "ActivePowerUnits", b1 =>
                        {
                            b1.Property<int>("InstructionCallId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PowerUnitId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InstructionCallId", "Id");

                            b1.ToTable("InstructionCalls");

                            b1.ToJson("ActivePowerUnits");

                            b1.WithOwner()
                                .HasForeignKey("InstructionCallId");
                        });

                    b.Navigation("ActiveAns");

                    b.Navigation("ActivePowerUnits");

                    b.Navigation("AggregationBlock");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.OfflineTelemetryReport", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.ReportFile", "AbCompositionFile")
                        .WithMany()
                        .HasForeignKey("AbCompositionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("OfflineTelemetryReports")
                        .HasForeignKey("AggregationBlockId");

                    b.HasOne("Terminal.Admin.Data.Models.ReportFile", "ArchiveFile")
                        .WithMany()
                        .HasForeignKey("ArchiveFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbCompositionFile");

                    b.Navigation("AggregationBlock");

                    b.Navigation("ArchiveFile");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.OperationPlanSlot", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany()
                        .HasForeignKey("AggregationBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Terminal.Admin.Data.Models.OperationPlanSlotPowerUnitActivity", "PowerUnitsActivity", b1 =>
                        {
                            b1.Property<int>("OperationPlanSlotId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PowerUnitId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OperationPlanSlotId", "Id");

                            b1.ToTable("OperationPlanSlots");

                            b1.ToJson("PowerUnitsActivity");

                            b1.WithOwner()
                                .HasForeignKey("OperationPlanSlotId");
                        });

                    b.Navigation("AggregationBlock");

                    b.Navigation("PowerUnitsActivity");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.PowerCalculation", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("Calculations")
                        .HasForeignKey("AggregationBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminal.Admin.Data.Models.CepsRequiredPower", "CepsRequiredPower")
                        .WithMany("Calculations")
                        .HasForeignKey("CepsRequiredPowerId");

                    b.Navigation("AggregationBlock");

                    b.Navigation("CepsRequiredPower");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.TelemetryLog", b =>
                {
                    b.HasOne("Terminal.Admin.Data.Models.AggregationBlock", "AggregationBlock")
                        .WithMany("Telemetry")
                        .HasForeignKey("AggregationBlockId");

                    b.HasOne("Terminal.Admin.Data.Models.PowerUnit", "PowerUnit")
                        .WithMany("Telemetry")
                        .HasForeignKey("PowerUnitId");

                    b.Navigation("AggregationBlock");

                    b.Navigation("PowerUnit");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.AggregationBlock", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("AggregationBlockPowerStates");

                    b.Navigation("BaselineValues");

                    b.Navigation("Calculations");

                    b.Navigation("CertificationsTests");

                    b.Navigation("FinishedChanges");

                    b.Navigation("OfflineTelemetryReports");

                    b.Navigation("RequiredPowers");

                    b.Navigation("Telemetry");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.CepsRequiredPower", b =>
                {
                    b.Navigation("Calculations");
                });

            modelBuilder.Entity("Terminal.Admin.Data.Models.PowerUnit", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
